# Generated by Django 4.0.3 on 2022-03-14 15:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('emblem', models.URLField()),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('number_of_players', models.CharField(choices=[('6', '6'), ('8', '8'), ('10', '10')], max_length=3)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
