# Generated by Django 4.0.3 on 2022-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
