# Generated by Django 4.0.3 on 2022-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_tournament_creator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
