# Generated by Django 4.0.3 on 2022-03-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_player_is_tournament_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2022, 3, 21)),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2022, 3, 21)),
        ),
    ]
