# Generated by Django 4.0.3 on 2022-03-21 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_tournament_end_date_tournament_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
    ]
