# Generated by Django 4.0.3 on 2022-03-22 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
    ]
