# Generated by Django 4.0.3 on 2022-03-23 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 23)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 3, 23)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 23)),
        ),
    ]
