# Generated by Django 4.0.3 on 2022-04-08 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_match_date_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
    ]
