# Generated by Django 4.0.3 on 2022-04-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_match_date_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tournament'),
        ),
    ]
