# Generated by Django 4.0.3 on 2022-04-10 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_match_away_team_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='continue_to_next_round',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
    ]
