# Generated by Django 4.0.3 on 2022-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_team_continue_to_next_round_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='web.team'),
        ),
    ]
