# Generated by Django 4.0.3 on 2022-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_tournament_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
