# Generated by Django 4.0.3 on 2022-04-13 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_match_date_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_goals',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_goals',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
